import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { Checkbox } from '@/app/common/ui/checkbox'
import { Card } from '@/app/common/ui/card'
import { Shield, Lock, Eye, Info } from 'lucide-react'
import { OnboardingActions } from './OnboardingActions'

export interface ParentalConsentStepProps {
  onConsent: () => void
}

export function ParentalConsentStep({ onConsent }: ParentalConsentStepProps) {
  const { t } = useTranslation()
  const [consented, setConsented] = useState(false)

  const handleContinue = () => {
    if (!consented) {
      return
    }
    onConsent()
  }

  return (
    <div className="max-w-2xl mx-auto">
      <Card className="p-8 bg-card shadow-lg rounded-2xl">
        <h1 className="text-3xl font-bold mb-4 text-foreground">
          {t('onboarding.parentalConsent.title', { defaultValue: 'Welcome to LogiKids' })}
        </h1>

        <p className="text-muted-foreground mb-6">
          {t('onboarding.parentalConsent.intro', {
            defaultValue: 'LogiKids uses AI to generate personalized learning tasks for your child.'
          })}
        </p>

        <div className="space-y-6 mb-6">
          <h2 className="text-xl font-semibold text-foreground mb-4">
            {t('onboarding.parentalConsent.keyPointsTitle', { defaultValue: 'Key Points' })}
          </h2>

          {/* Privacy-First - The main selling point */}
          <div className="bg-green-50 rounded-xl p-4 border border-green-200">
            <div className="flex items-start space-x-3">
              <Lock className="w-6 h-6 text-green-600 mt-0.5 shrink-0" />
              <div className="flex-1">
                <h3 className="font-semibold text-foreground mb-2">
                  {t('onboarding.parentalConsent.privacyTitle', {
                    defaultValue: 'Privacy-First: Your Data Stays Yours'
                  })}
                </h3>
                <p className="text-sm text-foreground leading-relaxed mb-2">
                  {t('onboarding.parentalConsent.privacyExplained', {
                    defaultValue: 'Unlike most apps, all your child\'s data is stored exclusively on your device. We use zero-knowledge encryption, which means even we cannot see your data - only you hold the keys.'
                  })}
                </p>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {t('onboarding.parentalConsent.privacyBackup', {
                    defaultValue: 'Optional cloud backup is available for convenience, but it\'s always encrypted on your device before being sent. The server only stores encrypted blobs that are meaningless without your key.'
                  })}
                </p>
              </div>
            </div>
          </div>

          {/* AI-Powered Learning */}
          <div className="flex items-start space-x-3">
            <Info className="w-5 h-5 text-primary mt-0.5 shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-foreground mb-1">
                {t('onboarding.parentalConsent.aiTitle', {
                  defaultValue: 'AI-Powered Personalized Learning'
                })}
              </h3>
              <p className="text-sm text-foreground leading-relaxed">
                {t('onboarding.parentalConsent.aiExplained', {
                  defaultValue: 'Every task is dynamically generated by AI to match your child\'s age, grade level, and learning pace. Content adapts to their progress, providing the right level of challenge at the right time.'
                })}
              </p>
            </div>
          </div>

          {/* Age-Appropriate Content */}
          <div className="flex items-start space-x-3">
            <Eye className="w-5 h-5 text-yellow-600 mt-0.5 shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-foreground mb-1">
                {t('onboarding.parentalConsent.contentTitle', {
                  defaultValue: 'Safe, Age-Appropriate Content'
                })}
              </h3>
              <p className="text-sm text-foreground leading-relaxed">
                {t('onboarding.parentalConsent.contentExplained', {
                  defaultValue: 'All content is filtered and validated to ensure it\'s appropriate for your child\'s age. Our prompts are designed to generate educational, safe content focused purely on learning.'
                })}
              </p>
            </div>
          </div>

          {/* Compliance & Rights */}
          <div className="flex items-start space-x-3">
            <Shield className="w-5 h-5 text-purple-600 mt-0.5 shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-foreground mb-1">
                {t('onboarding.parentalConsent.complianceTitle', {
                  defaultValue: 'GDPR & AI Act Compliant'
                })}
              </h3>
              <p className="text-sm text-foreground leading-relaxed">
                {t('onboarding.parentalConsent.complianceExplained', {
                  defaultValue: 'Full compliance with GDPR regulations and the EU AI Act. You have the right to access, export, or delete all data at any time. No third-party data sharing, ever.'
                })}
              </p>
            </div>
          </div>
        </div>

        <div className="bg-primary/10 rounded-xl p-4 mb-6 space-y-3">
          <div className="flex items-start space-x-2">
            <Checkbox
              id="consent"
              checked={consented}
              onCheckedChange={(checked) => setConsented(checked === true)}
              className="mt-0.5"
            />
            <label
              htmlFor="consent"
              className="text-sm font-medium text-foreground cursor-pointer leading-relaxed"
            >
              {t('onboarding.parentalConsent.consentCheckbox', {
                defaultValue: 'I am a parent/guardian and confirm that I have read and understood the above information. I understand that this app uses AI to generate educational content and I agree to provide appropriate parental supervision during use.'
              })}
            </label>
          </div>
        </div>

        <OnboardingActions
          onContinue={handleContinue}
          continueLabel={t('onboarding.parentalConsent.continue', { defaultValue: 'Continue' })}
          continueDisabled={!consented}
          continueIcon={true}
          footer={
            <div className="text-sm text-center space-x-4">
              <Link
                to="/privacy"
                className="text-primary hover:underline"
              >
                {t('onboarding.parentalConsent.privacyPolicy', { defaultValue: 'Privacy Policy' })}
              </Link>
              <Link
                to="/impressum"
                className="text-primary hover:underline"
              >
                {t('footer.impressum', { defaultValue: 'Legal Notice' })}
              </Link>
            </div>
          }
        />
      </Card>
    </div>
  )
}
