-- Migration: Add user accounts and update invite system
-- Created: 2025-11-02
-- Description: Store user accounts linked to invite codes, prevent invite reuse

-- Add columns to invite_codes for tracking usage
ALTER TABLE invite_codes
  ADD COLUMN IF NOT EXISTS used_by TEXT,
  ADD COLUMN IF NOT EXISTS used_at BIGINT;

-- Create user_accounts table
CREATE TABLE IF NOT EXISTS user_accounts (
  user_id TEXT PRIMARY KEY,
  invite_code TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  last_seen BIGINT NOT NULL,
  CONSTRAINT fk_invite_code FOREIGN KEY (invite_code) REFERENCES invite_codes(code)
);

-- Index for lookups
CREATE INDEX IF NOT EXISTS idx_user_accounts_invite ON user_accounts(invite_code);
CREATE INDEX IF NOT EXISTS idx_invite_codes_used_by ON invite_codes(used_by);

-- Comments for documentation
COMMENT ON TABLE user_accounts IS 'User accounts created via invite codes';
COMMENT ON COLUMN user_accounts.user_id IS 'UUID generated by client, unique per user';
COMMENT ON COLUMN user_accounts.invite_code IS 'Invite code used to create this account';
COMMENT ON COLUMN user_accounts.created_at IS 'Unix timestamp (ms) when account was created';
COMMENT ON COLUMN user_accounts.last_seen IS 'Unix timestamp (ms) of last API request';

COMMENT ON COLUMN invite_codes.used_by IS 'User ID that used this invite code (NULL if unused)';
COMMENT ON COLUMN invite_codes.used_at IS 'Unix timestamp (ms) when code was used (NULL if unused)';
