import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Card } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Shield, Lock, Eye, UserX, Info } from 'lucide-react'

export interface ParentalConsentStepProps {
  onConsent: (inviteCode: string) => void
}

export function ParentalConsentStep({ onConsent }: ParentalConsentStepProps) {
  const { t } = useTranslation()
  const [consented, setConsented] = useState(false)
  const [inviteCode, setInviteCode] = useState('')
  const [isValidating, setIsValidating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleContinue = async () => {
    if (!consented || !inviteCode.trim()) {
      return
    }

    setIsValidating(true)
    setError(null)

    try {
      const apiUrl = import.meta.env.VITE_API_URL || 'http://localhost:5175'
      // Use /check endpoint to validate WITHOUT deleting the code
      const response = await fetch(`${apiUrl}/api/invite/check`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: inviteCode.trim() })
      })

      const result = await response.json()

      if (result.valid) {
        // Pass the code to parent - it will be deleted after account creation
        onConsent(inviteCode.trim())
      } else {
        setError(result.reason || 'Invalid invite code')
      }
    } catch (err) {
      setError('Failed to validate invite code. Please try again.')
      console.error('Invite validation error:', err)
    } finally {
      setIsValidating(false)
    }
  }

  return (
    <div className="max-w-2xl mx-auto">
      <Card className="p-8 bg-white shadow-lg rounded-2xl">
        <h1 className="text-3xl font-bold mb-4 text-gray-900">
          {t('onboarding.parentalConsent.title', { defaultValue: 'Welcome to LogiKids' })}
        </h1>

        <p className="text-gray-600 mb-6">
          {t('onboarding.parentalConsent.intro', {
            defaultValue: 'LogiKids uses AI to generate personalized learning tasks for your child.'
          })}
        </p>

        <div className="space-y-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            {t('onboarding.parentalConsent.keyPointsTitle', { defaultValue: 'Key Points' })}
          </h2>

          {/* Privacy-First - The main selling point */}
          <div className="bg-green-50 rounded-xl p-4 border border-green-200">
            <div className="flex items-start space-x-3">
              <Lock className="w-6 h-6 text-green-600 mt-0.5 shrink-0" />
              <div className="flex-1">
                <h3 className="font-semibold text-gray-900 mb-2">
                  {t('onboarding.parentalConsent.privacyTitle', {
                    defaultValue: 'Privacy-First: Your Data Stays Yours'
                  })}
                </h3>
                <p className="text-sm text-gray-700 leading-relaxed mb-2">
                  {t('onboarding.parentalConsent.privacyExplained', {
                    defaultValue: 'Unlike most apps, all your child\'s data is stored exclusively on your device. We use zero-knowledge encryption, which means even we cannot see your data - only you hold the keys.'
                  })}
                </p>
                <p className="text-sm text-gray-600 leading-relaxed">
                  {t('onboarding.parentalConsent.privacyBackup', {
                    defaultValue: 'Optional cloud backup is available for convenience, but it\'s always encrypted on your device before being sent. The server only stores encrypted blobs that are meaningless without your key.'
                  })}
                </p>
              </div>
            </div>
          </div>

          {/* AI-Powered Learning */}
          <div className="flex items-start space-x-3">
            <Info className="w-5 h-5 text-primary mt-0.5 shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-gray-900 mb-1">
                {t('onboarding.parentalConsent.aiTitle', {
                  defaultValue: 'AI-Powered Personalized Learning'
                })}
              </h3>
              <p className="text-sm text-gray-700 leading-relaxed">
                {t('onboarding.parentalConsent.aiExplained', {
                  defaultValue: 'Every task is dynamically generated by AI to match your child\'s age, grade level, and learning pace. Content adapts to their progress, providing the right level of challenge at the right time.'
                })}
              </p>
            </div>
          </div>

          {/* Age-Appropriate Content */}
          <div className="flex items-start space-x-3">
            <Eye className="w-5 h-5 text-yellow-600 mt-0.5 shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-gray-900 mb-1">
                {t('onboarding.parentalConsent.contentTitle', {
                  defaultValue: 'Safe, Age-Appropriate Content'
                })}
              </h3>
              <p className="text-sm text-gray-700 leading-relaxed">
                {t('onboarding.parentalConsent.contentExplained', {
                  defaultValue: 'All content is filtered and validated to ensure it\'s appropriate for your child\'s age. Our prompts are designed to generate educational, safe content focused purely on learning.'
                })}
              </p>
            </div>
          </div>

          {/* Compliance & Rights */}
          <div className="flex items-start space-x-3">
            <Shield className="w-5 h-5 text-purple-600 mt-0.5 shrink-0" />
            <div className="flex-1">
              <h3 className="font-semibold text-gray-900 mb-1">
                {t('onboarding.parentalConsent.complianceTitle', {
                  defaultValue: 'GDPR & AI Act Compliant'
                })}
              </h3>
              <p className="text-sm text-gray-700 leading-relaxed">
                {t('onboarding.parentalConsent.complianceExplained', {
                  defaultValue: 'Full compliance with GDPR regulations and the EU AI Act. You have the right to access, export, or delete all data at any time. No third-party data sharing, ever.'
                })}
              </p>
            </div>
          </div>
        </div>

        <div className="bg-blue-50 rounded-xl p-4 mb-6 border border-blue-200">
          <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <Shield className="w-5 h-5 text-blue-600" />
            {t('onboarding.parentalConsent.inviteTitle', { defaultValue: 'Invite Code Required' })}
          </h3>
          <p className="text-sm text-gray-700 mb-4">
            {t('onboarding.parentalConsent.inviteExplained', {
              defaultValue: 'LogiKids is currently in closed beta. Please enter the invite code you received to continue.'
            })}
          </p>
          <Input
            placeholder={t('onboarding.parentalConsent.invitePlaceholder', { defaultValue: 'Enter invite code (e.g., ABCD-1234)' })}
            value={inviteCode}
            onChange={(e) => {
              setInviteCode(e.target.value.toUpperCase())
              setError(null)
            }}
            className="font-mono text-center tracking-wider"
            maxLength={9}
          />
          {error && (
            <p className="text-sm text-red-600 mt-2">
              ❌ {error}
            </p>
          )}
        </div>

        <div className="bg-primary/10 rounded-xl p-4 mb-6 space-y-3">
          <div className="flex items-start space-x-2">
            <Checkbox
              id="consent"
              checked={consented}
              onCheckedChange={(checked) => setConsented(checked === true)}
              className="mt-0.5"
            />
            <label
              htmlFor="consent"
              className="text-sm font-medium text-gray-900 cursor-pointer leading-relaxed"
            >
              {t('onboarding.parentalConsent.consentCheckbox', {
                defaultValue: 'I am a parent/guardian and confirm that I have read and understood the above information. I understand that this app uses AI to generate educational content and I agree to provide appropriate parental supervision during use.'
              })}
            </label>
          </div>
        </div>

        <div className="flex justify-between items-center">
          <div className="text-sm space-x-4">
            <a
              href="#"
              className="text-primary hover:underline"
              onClick={(e) => e.preventDefault()}
            >
              {t('onboarding.parentalConsent.privacyPolicy', { defaultValue: 'Privacy Policy' })}
            </a>
            <a
              href="#"
              className="text-primary hover:underline"
              onClick={(e) => e.preventDefault()}
            >
              {t('onboarding.parentalConsent.terms', { defaultValue: 'Terms of Service' })}
            </a>
          </div>

          <Button
            onClick={handleContinue}
            disabled={!consented || !inviteCode.trim() || isValidating}
            size="lg"
          >
            {isValidating
              ? t('onboarding.parentalConsent.validating', { defaultValue: 'Validating...' })
              : t('onboarding.parentalConsent.continue', { defaultValue: 'Continue' })
            }
          </Button>
        </div>
      </Card>
    </div>
  )
}
